M48
; DRILL file {KiCad 9.0.4} date 2026-06-01T19:18:13-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-06-01T19:18:13-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0335
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0866
%
G90
G05
T1
X3.6862Y-4.7974
X3.9138Y-4.7974
T2
X2.7Y-4.0809
X2.7Y-4.1991
T3
X2.72Y-3.38
X3.38Y-4.42
X4.8769Y-3.3806
M30
